version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 3050:3050
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: